drop table if exists RECIPE;
drop table if exists DOCTOR;
drop table if exists PATIENT;

create table DOCTOR(
    id bigint generated by default as identity(start with 1) not null,
    name varchar(20) not null,
    middle_name varchar(20) not null ,
    last_name varchar(20) not null,
    specialization varchar(30) not null,
    primary key (id)
);

create table PATIENT (
    id bigint generated by default as identity (start with 1) not null,
    name varchar(20) not null,
    middle_name varchar(20) not null,
    last_name varchar(20) not null,
    phone varchar(11) not null,
    primary key (id)
);

create table RECIPE (
    id bigint generated  by default as identity (start with 1) not null,
    description varchar(100),
    date_creation date,
    date_expiration date,
    priority varchar(6),
    id_patient bigint,
    id_doctor bigint,
    primary key (id),
    constraint fk_doctorid foreign key (id_doctor) references DOCTOR(id),
    constraint fk_patientid foreign key (id_patient) references PATIENT(id)
);

insert into DOCTOR (name, middle_name, last_name, specialization) VALUES ('Sasha', 'Andrey', 'Levin', 'Dentist'),
                                                                         ('Andrey', 'Alexander', 'Barov', 'Surgeon'),
                                                                         ('Grisha', 'Alexey', 'Zubov', 'Therapist'),
                                                                         ('Ivan', 'Vladimir', 'Minaev', 'Dentist'),
                                                                         ('Mikhail', 'Sergey', 'Stanov', 'Traumatologist');

insert into PATIENT (name, middle_name, last_name, phone) values ('Alexander', 'Vyacheslav', 'Semdyanov', '89245012869'),
                                                                 ('Vladimir', 'Dmitri', 'Mavlyutov', '89028900000'),
                                                                 ('Nikita', 'Dmitri', 'Perevozchikov', '89331105491'),
                                                                 ('Tatyana', 'Nikolay', 'Venediktova', '89520198521'),
                                                                 ('Elena', 'Nikolay', 'Bykova', '89521850021');

insert into RECIPE (description, date_creation, date_expiration, priority, id_patient, id_doctor) values ('paracetamol two times per day', '2019-05-05', '2019-06-05', 'NORMAL', 1, 1),
                                                                                                         ('only expensive pills', '2019-04-01', '2019-05-12', 'CITO', 2, 1),
                                                                                                         ('any cheap pills', '2019-06-06', '2019-10-24', 'STATIM', 3, 1),
                                                                                                         ('two packs of ascorbate', '2019-05-07', '2019-05-19', 'NORMAL', 4, 2),
                                                                                                         ('just water', '2019-05-12', '2020-05-12', 'NORMAL', 4, 3);